name: Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Define environment variables at workflow level
env:
  DOCKER_REGISTRY: docker.io

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Docker
        run: |
          docker version
          docker compose version || docker --help

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and deploy with Compose
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Build local image and (re)create service
          docker compose up -d --build

      - name: Show running containers
        run: |
          docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'