name: Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DOCKERFILE: Dockerfile

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      # Fix permissions before checkout
      - name: Fix permissions
        run: |
          # Fix permissions in the workspace directory
          mkdir -p $GITHUB_WORKSPACE
          chmod -R 777 $GITHUB_WORKSPACE || true
          
          # Make sure git directory is clean
          if [ -d "$GITHUB_WORKSPACE/.git" ]; then
            rm -rf $GITHUB_WORKSPACE/.git || true
          fi
          
          # Ensure workflows directory is writable
          if [ -d "$GITHUB_WORKSPACE/.github/workflows" ]; then
            sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE/.github
            chmod -R 777 $GITHUB_WORKSPACE/.github || true
          fi
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          
      - name: Post-checkout permission fix
        run: |
          # Fix Git directory permissions after checkout
          chmod -R 777 $GITHUB_WORKSPACE/.git || true
          
          # Configure Git to trust the workspace directory
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
