name: Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DOCKERFILE: Dockerfile

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      - name: setup-workspace
        run: |
          rm -rf /__w
          mkdir -p /__w
          mkdir -p /__w/_temp
          mkdir -p /__w/_actions
          mkdir -p /__w/_tool
          mkdir -p /__w/_work

          chmod 777 /__w/_temp 2>/dev/null || true
          chmod 777 /__w/_actions 2>/dev/null || true
          chmod 777 /__w/_tool 2>/dev/null || true
          chmod 777 /__w/_work 2>/dev/null || true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
