name: Nix

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    container:
      image: nixos/nix:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: setup-workspace
        run: |
          rm -rf /__w
          mkdir -p /__w
          mkdir -p /__w/_temp
          mkdir -p /__w/_actions
          mkdir -p /__w/_tool
          mkdir -p /__w/_work

          chmod 777 /__w/_temp 2>/dev/null || true
          chmod 777 /__w/_actions 2>/dev/null || true
          chmod 777 /__w/_tool 2>/dev/null || true
          chmod 777 /__w/_work 2>/dev/null || true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
      - name: Install dependencies
        run: |
          # Install git and cacert
          nix-env -iA nixpkgs.git nixpkgs.cacert
          git config --global --add safe.directory "${{ secrets.RUNNER_WORKSPACE }}"
          
          # Install Node.js for GitHub Actions
          nix-env -iA nixpkgs.nodejs
          mkdir -p /__e/node20/bin
          ln -sf $(which node) /__e/node20/bin/node

      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Nix flake show
        run: nix flake show

      - name: Build in devshell (sanity)
        run: |
          nix develop -c bash -lc "rustup show || true; cargo --version || true; cargo build -q"
