name: Rust CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy,rustfmt

      - name: Install nightly for Wasm runtime
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Cargo fmt check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build (includes runtime Wasm via wasm-builder)
        env:
          WASM_BUILD_TOOLCHAIN: nightly
        run: cargo build --locked --release

      - name: Test
        env:
          WASM_BUILD_TOOLCHAIN: nightly
        run: cargo test --all --locked --release -- --nocapture
