name: Rust CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    container:
      image: rust:1-bookworm
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            ca-certificates \
            clang \
            cmake \
            curl \
            git \
            libssl-dev \
            pkg-config \
            xz-utils \
            sudo
          
          # Install Nix
          curl -L https://nixos.org/nix/install | sh -s -- --daemon --yes
          . /root/.nix-profile/etc/profile.d/nix.sh
          echo "source /root/.nix-profile/etc/profile.d/nix.sh" >> ~/.bashrc

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Run CI script
        run: ./scripts/run_ci.sh
        env:
          WASM_BUILD_TOOLCHAIN: nightly
